package com.snrtqi.buy.pojo;

import java.math.BigDecimal;

public class Orderitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.iid
     *
     * @mbggenerated
     */
    private String iid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.subtotal
     *
     * @mbggenerated
     */
    private BigDecimal subtotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oid
     *
     * @mbggenerated
     */
    private String oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.bid
     *
     * @mbggenerated
     */
    private String bid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.iid
     *
     * @return the value of orderitem.iid
     *
     * @mbggenerated
     */
    public String getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.iid
     *
     * @param iid the value for orderitem.iid
     *
     * @mbggenerated
     */
    public void setIid(String iid) {
        this.iid = iid == null ? null : iid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.count
     *
     * @return the value of orderitem.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.count
     *
     * @param count the value for orderitem.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.subtotal
     *
     * @return the value of orderitem.subtotal
     *
     * @mbggenerated
     */
    public BigDecimal getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.subtotal
     *
     * @param subtotal the value for orderitem.subtotal
     *
     * @mbggenerated
     */
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oid
     *
     * @return the value of orderitem.oid
     *
     * @mbggenerated
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oid
     *
     * @param oid the value for orderitem.oid
     *
     * @mbggenerated
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.bid
     *
     * @return the value of orderitem.bid
     *
     * @mbggenerated
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.bid
     *
     * @param bid the value for orderitem.bid
     *
     * @mbggenerated
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }
}